(prev commit)director will not attempt to draw if the window has area zero
This change fixes crashes in tests
test_fadeouttiles_tr.py
test_accel_amplitude.py
and probably others:

If you minimized the window when the transition has ended, the app crashed with:
 [snip]
 File "H:\cocos_pristine\cocos_dev\cocos_released\test\..\cocos\grid.py", line
170, in _set_3d_projection
 gluPerspective(60, 1.0*width/height, 0.1, 3000.0)
ZeroDivisionError: float division

When minimized, at least in windows, you have director.windows.height==0, thus crashing
But there is no reason to draw if the window area is zero. 

git-svn-id: http://los-cocos.googlecode.com/svn/trunk@946 f663ce52-ac46-0410-b8de-c1c220b0eb76